import { Server as HttpServer } from 'node:http';
import { WebSocketServer, WebSocket } from 'ws';
import { configService } from './config.service';

// Generated by Copilot

/**
 * Payload shape for websocket events sent to extension clients.
 */
interface WsEventPayload<T = Record<string, unknown>> {
  type: "UPDATE" | "ONLINE" | "SESSION_STARTED";
  data?: T;
}

/**
 * Singleton-style websocket service for system-app realtime events.
 */
class WsService {
  private wss: WebSocketServer | null = null;

  /**
   * Singleton Setup
   */
  private constructor() { }
  private static instance: WsService;
  public static getInstance(): WsService {
    if (!WsService.instance) {
      WsService.instance = new WsService();
    }
    return WsService.instance;
  }

  /**
   * Initializes websocket server and attaches it to an existing HTTP server.
   * @param {HttpServer} server - Node HTTP server instance.
   * @returns {void}
   */
  init(server: HttpServer): void {
    // if the websocket server is already initialized, we don't want to make another
    if (this.wss) return;

    // initialize the websocket server and set up connection handling
    this.wss = new WebSocketServer({ server, path: '/ws' });

    // when a new client connects, we want to send them the current configuration and an "online" event
    this.wss.on('connection', (socket) => {
      this.sendToSocket(socket, {
        type: 'ONLINE'
      });
      this.sendToSocket(socket, {
        type: 'UPDATE',
        data: {
          config: configService.config
        }
      });
    });
  }


  /**
   * Broadcasts an event payload to every connected websocket client.
   * @param {WsEventPayload} payload - Event payload to broadcast.
   * @returns {void}
   */
  broadcast(payload: WsEventPayload): void {
    // We must have a websocket server to broadcast messages, so if we don't have one, we can't do anything
    if (!this.wss) return;

    const serializedPayload = JSON.stringify(payload);
    this.wss.clients.forEach((client) => {
      client.readyState === WebSocket.OPEN ? client.send(serializedPayload) : undefined;
    });
  }

  /**
   * Sends a websocket payload to a single socket.
   * @param {WebSocket} socket - Connected websocket client.
   * @param {WsEventPayload} payload - Payload to send.
   * @returns {void}
   */
  private sendToSocket(socket: WebSocket, payload: WsEventPayload): void {
    socket.readyState === WebSocket.OPEN ? socket.send(JSON.stringify(payload)) : undefined;
  }
}

export const wsService = WsService.getInstance();
