import { createApp } from './app';
import { env } from './utils/env';
import { configService } from './services/config.service';
import { wsService } from './services/ws.service';
import { fork } from 'node:child_process';
import path from 'node:path';
import sessionService from './services/session.service';

// Generated by Copilot


const bootstrap = () => {
  try {
    const loadedConfig = configService.loadFromFile(env.installConfigFile);

    console.log("Loaded installation config:", loadedConfig);

    const app = createApp();
    const server = app.listen(env.port, '127.0.0.1', () => {
      console.log(`System app listening on http://127.0.0.1:${env.port}`);
      const trayLauncherPath = path.join(__dirname, 'tray-launcher.js');
      const trayProcess = fork(trayLauncherPath, [], {
        env: {
          ...process.env,
          SYSTEM_APP_PORT: String(env.port)
        }
      });

      trayProcess.on('message', (message: { type?: string } | unknown) => {
        if ((message as { type?: string })?.type !== 'quit') return;
        server.close(() => process.exit(0));
      });

      trayProcess.on('exit', (code) => {
        if (code === 0) return;
        console.warn(`Tray process exited with code ${code ?? -1}`);
      });
    });
    wsService.init(server);
  } catch (error) {
    console.error("Failed to load installation config:", error);
    process.exit(1);
  }
};

void bootstrap();
